package com.github.rmelick.memory;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class.getName());
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LOGGER.info("Starting application");
    }
}
